#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The xdiag Contributors
"""
Triangular lattice TOML generator with a two-site unit cell.

Bravais vectors of the superlattice:
  b1 = a1
  b2 = 2*a2

Basis (two sites per cell):
  tau0 = 0
  tau1 = a2 = 0.5*b2
"""

import argparse
from collections import deque
import numpy as np

_SQRT3 = np.sqrt(3.0)

# Original triangular vectors (requested geometry)
_a1 = np.array([0.5, _SQRT3 / 2.0])
_a2 = np.array([-0.5, _SQRT3 / 2.0])

# New primitive vectors
_b1_lat = np.array([1, 0], dtype=int)   # in (a1,a2) coordinates
_b2_lat = np.array([0, 2], dtype=int)   # = 2*a2
_b1 = _a1
_b2 = 2.0 * _a2

# Two-site basis in (a1,a2)-lattice coordinates
_tau_lat = {
    0: np.array([0, 0], dtype=int),
    1: np.array([0, 1], dtype=int),  # a2
}

# Reciprocal vectors of (b1,b2)
_BMAT = np.column_stack((_b1, _b2))
_RECIP = 2.0 * np.pi * np.linalg.inv(_BMAT).T
_rb1 = _RECIP[:, 0]
_rb2 = _RECIP[:, 1]


def lat_to_cart(site):
    """site = (n1, n2, sub) with cell coords in (b1,b2)-basis."""
    n1, n2, sub = site
    # Convert to (a1,a2) integer coords:
    # n1*b1 + n2*b2 + tau_sub = (n1, 2*n2) + tau_sub in (a1,a2)
    av = np.array([n1, 2 * n2], dtype=float) + _tau_lat[sub]
    return av[0] * _a1 + av[1] * _a2


def _recip_cart(q1, q2):
    k = q1 * _rb1 + q2 * _rb2
    return float(k[0]), float(k[1])


def _enumerate_cells(a, b, TinvN, ncell):
    rng = abs(a) + abs(b) + 1
    cells = []
    for n2 in range(-rng, rng + 1):
        for n1 in range(-rng, rng + 1):
            f = TinvN @ np.array([n1, n2], dtype=int)
            if 0 <= int(f[0]) < ncell and 0 <= int(f[1]) < ncell:
                cells.append((n1, n2))
    if len(cells) != ncell:
        raise RuntimeError(f"Expected {ncell} cells, got {len(cells)}")
    cells.sort(key=lambda v: tuple(int(x) for x in TinvN @ np.array(v, dtype=int)))
    return cells


def build_torus(a, b):
    """
    Torus in cell coordinates (b1,b2):
      T = [[a,b],[-b,a-b]]
    """
    ncell = a * a - a * b + b * b
    if ncell <= 0:
        raise ValueError(f"(a={a}, b={b}) gives Ncell={ncell} <= 0")

    T = np.array([[a, b], [-b, a - b]], dtype=int)
    TinvN = np.array([[a - b, -b], [b, a]], dtype=int)

    cells = _enumerate_cells(a, b, TinvN, ncell)
    sites = []
    for n1, n2 in cells:
        sites.append((n1, n2, 0))
        sites.append((n1, n2, 1))

    nsite = 2 * ncell
    return cells, sites, T, TinvN, ncell, nsite


def _frac_mod_cell(v, TinvN, ncell):
    f = TinvN @ np.array(v, dtype=int)
    return (int(f[0]) % ncell, int(f[1]) % ncell)


def _build_lookup(sites, TinvN, ncell):
    return {
        (_frac_mod_cell((n1, n2), TinvN, ncell), sub): idx
        for idx, (n1, n2, sub) in enumerate(sites)
    }


def compute_translation_perm(sites, TinvN, ncell, delta):
    lookup = _build_lookup(sites, TinvN, ncell)
    perm = []
    for n1, n2, sub in sites:
        key = (_frac_mod_cell((n1 + delta[0], n2 + delta[1]), TinvN, ncell), sub)
        perm.append(lookup[key])
    return perm


def build_symmetries(sites, cells, TinvN, ncell):
    # Full translation group of new Bravais lattice generated by b1,b2
    syms = []
    for d1, d2 in cells:
        syms.append(compute_translation_perm(sites, TinvN, ncell, (d1, d2)))
    return syms, cells


def _site_to_a_coords(site):
    n1, n2, sub = site
    return (n1, 2 * n2 + sub)


def _a_coords_to_site(m1, m2):
    sub = m2 % 2
    n2 = (m2 - sub) // 2
    n1 = m1
    return (n1, n2, sub)


def compute_nn_bonds(sites, TinvN, ncell):
    # NN in original triangular coords
    nn_dirs = [(1, 0), (0, 1), (1, -1)]
    lookup = _build_lookup(sites, TinvN, ncell)
    bonds = []
    for i, s in enumerate(sites):
        m1, m2 = _site_to_a_coords(s)
        for d1, d2 in nn_dirs:
            t = _a_coords_to_site(m1 + d1, m2 + d2)
            key = (_frac_mod_cell((t[0], t[1]), TinvN, ncell), t[2])
            j = lookup[key]
            bonds.append((i, j))
    return bonds

def _site_index_from_a_coords(m1, m2, lookup, TinvN, ncell):
    """Map an (a1,a2) integer coordinate to torus-wrapped site index."""
    n1, n2, sub = _a_coords_to_site(m1, m2)
    key = (_frac_mod_cell((n1, n2), TinvN, ncell), sub)
    return lookup[key]


def triangles(sites, TinvN, ncell):
    """
    Return all unique elementary triangles (unordered index triplets).

    Triangles are generated from the two primitive plaquettes:
      up   : (m, m+e1,     m+e2)
      down : (m, m+e1, m+e1-e2)
    in (a1,a2) integer coordinates.
    """
    lookup = _build_lookup(sites, TinvN, ncell)
    tri_set = set()

    for site in sites:
        m1, m2 = _site_to_a_coords(site)

        # Up triangle
        i = _site_index_from_a_coords(m1, m2, lookup, TinvN, ncell)
        j = _site_index_from_a_coords(m1 + 1, m2, lookup, TinvN, ncell)
        k = _site_index_from_a_coords(m1, m2 + 1, lookup, TinvN, ncell)
        tri_set.add(tuple(sorted((i, j, k))))

        # Down triangle
        i2 = i
        j2 = _site_index_from_a_coords(m1 + 1, m2, lookup, TinvN, ncell)
        k2 = _site_index_from_a_coords(m1 + 1, m2 - 1, lookup, TinvN, ncell)
        tri_set.add(tuple(sorted((i2, j2, k2))))

    return sorted(tri_set)


def _triangle_orientation_sign(cycle, sites):
    """
    Signed area proxy for cycle (i,j,k) in Euclidean embedding.
    Positive -> anti-clockwise, negative -> clockwise.
    """
    i, j, k = cycle
    ri = lat_to_cart(sites[i])
    rj = lat_to_cart(sites[j])
    rk = lat_to_cart(sites[k])

    v1 = rj - ri
    v2 = rk - ri
    return float(v1[0] * v2[1] - v1[1] * v2[0])


def chiralorder(triangle, orientation, sites):
    """
    Return the 3 cyclic permutations corresponding to the requested loop orientation.

    Parameters
    ----------
    triangle : iterable of 3 site indices
    orientation : str in {"clockwise","anti-clockwise","cw","ccw","up","down"}
        aliases: up->anti-clockwise, down->clockwise
    sites : site list from build_torus()

    Returns
    -------
    list[(i,j,k), (j,k,i), (k,i,j)] with requested orientation.
    """
    tri = tuple(triangle)
    if len(tri) != 3:
        raise ValueError("triangle must contain exactly 3 site indices")

    ori = orientation.strip().lower()
    if ori in {"anti-clockwise", "anticlockwise", "ccw", "up"}:
        want_ccw = True
    elif ori in {"clockwise", "cw", "down"}:
        want_ccw = False
    else:
        raise ValueError(f"Unknown orientation '{orientation}'")

    a, b, c = tri

    # Candidate cycles; exactly one orientation class is cyclicly equivalent.
    cyc1 = (a, b, c)
    cyc2 = (a, c, b)

    sign1 = _triangle_orientation_sign(cyc1, sites)
    use = cyc1 if ((sign1 > 0) == want_ccw) else cyc2

    i, j, k = use
    return [(i, j, k), (j, k, i), (k, i, j)]


def genSSC(tris, orientations, sites, coupling_name="Jchi"):
    """
    Generate ScalarChirality terms from triangles and per-triangle orientation labels.

    Parameters
    ----------
    tris : list[triangle]
    orientations : list[str]
        One orientation label per triangle (e.g. all 'up' for testing).
    sites : site list from build_torus()
    coupling_name : str
    """
    if len(orientations) != len(tris):
        raise ValueError(
            f"orientations length ({len(orientations)}) != number of triangles ({len(tris)})"
        )

    interactions = []
    for tri, ori in zip(tris, orientations):
        for i, j, k in chiralorder(tri, ori, sites):
            interactions.append((coupling_name, "ScalarChirality", i, j, k))
    return interactions

def compute_nnn_bonds_unique(sites, TinvN, ncell):
    # Half set of NNN directions in original triangular coords
    nnn_dirs = [(1, 1), (2, -1), (1, -2)]
    lookup = _build_lookup(sites, TinvN, ncell)
    pairs = set()
    for i, s in enumerate(sites):
        m1, m2 = _site_to_a_coords(s)
        for d1, d2 in nnn_dirs:
            t = _a_coords_to_site(m1 + d1, m2 + d2)
            key = (_frac_mod_cell((t[0], t[1]), TinvN, ncell), t[2])
            j = lookup[key]
            pair = (i, j) if i < j else (j, i)
            pairs.add(pair)
    return sorted(pairs)


def enumerate_momenta(a, b, ncell):
    rng = abs(a) + abs(b) + 1
    out = []
    for m2 in range(-rng, rng + 1):
        for m1 in range(-rng, rng + 1):
            fq1 = (a - b) * m1 + b * m2
            fq2 = -b * m1 + a * m2
            if 0 <= fq1 < ncell and 0 <= fq2 < ncell:
                q1, q2 = fq1 / ncell, fq2 / ncell
                kx, ky = _recip_cart(q1, q2)
                out.append((fq1, fq2, q1, q2, kx, ky))
    if len(out) != ncell:
        raise RuntimeError(f"Expected {ncell} momenta, got {len(out)}")
    out.sort(key=lambda x: (x[0], x[1]))
    return out


def _clean_char(z, tol=1e-12):
    re, im = z.real, z.imag
    for exact in (0.0, 1.0, -1.0, 0.5, -0.5, _SQRT3 / 2.0, -_SQRT3 / 2.0):
        if abs(re - exact) < tol:
            re = exact
        if abs(im - exact) < tol:
            im = exact
    return complex(re, im)


def _char_key(chars, ndigits=12):
    return tuple((round(c.real, ndigits), round(c.imag, ndigits)) for c in chars)


def compute_irrep_sections(a, b, ncell, displacements):
    sections = []
    seen = set()
    for _, _, q1, q2, kx, ky in enumerate_momenta(a, b, ncell):
        chars = [
            _clean_char(np.exp(2j * np.pi * (q1 * d1 + q2 * d2)))
            for d1, d2 in displacements
        ]
        key = _char_key(chars)
        if key in seen:
            continue
        seen.add(key)
        sections.append({
            "name": f"k{len(sections) + 1}",
            "characters": chars,
            "momentum": [kx, ky],
        })
    return sections


def verify_perm(perm, name="perm"):
    n = len(perm)
    if sorted(perm) != list(range(n)):
        raise AssertionError(f"{name} is not a permutation")


def verify_sections(symmetries, sections, tol=1e-8):
    hsize = len(symmetries)
    if len(sections) != hsize:
        raise AssertionError(f"Expected {hsize} irreps, got {len(sections)}")
    chi = np.array([s["characters"] for s in sections], dtype=complex)
    gram = (chi @ chi.conj().T) / hsize
    err = np.max(np.abs(gram - np.eye(hsize)))
    if err > tol:
        raise AssertionError(f"Orthogonality failed: {err:.3e}")


def write_toml(
        filename, sites, T, TinvN, ncell, nsite, a, b,
        perm_ta1, perm_t2a2, symmetries, displacements,
        j1_name="J1", j2_name="J2", jchi_name="Jchi", chiral_orientations=None
):
    nn = compute_nn_bonds(sites, TinvN, ncell)
    nnn = compute_nnn_bonds_unique(sites, TinvN, ncell)
    tris = triangles(sites, TinvN, ncell)

    # Default testing pattern: all triangles "up" (anti-clockwise loops)
    if chiral_orientations is None:
        chiral_orientations = ["up"] * len(tris)

    ssc = genSSC(tris, chiral_orientations, sites, coupling_name=jchi_name)
    sections = compute_irrep_sections(a, b, ncell, displacements)


    with open(filename, "w", encoding="utf-8") as f:
        f.write("# Triangular lattice with 2-site unit cell\n")
        f.write("# Primitive vectors: b1=a1, b2=2*a2\n")
        f.write(f"# Parameters: a={a}, b={b}, Ncell={ncell}, Nsite={nsite}\n")
        f.write(f"# Torus vectors (cell coords): t1=({T[0,0]},{T[1,0]}), t2=({T[0,1]},{T[1,1]})\n")
        f.write("# Generated by genlat_triangular_tonly.py\n\n")

        f.write("Coordinates = [\n")
        for s in sites:
            c = lat_to_cart(s)
            f.write(f"  [{c[0]:.15f}, {c[1]:.15f}],\n")
        f.write("]\n\n")

        f.write(
            "# Interactions: NN + NNN Heisenberg + ScalarChirality "
            f"({len(nn)} + {len(nnn)} + {len(ssc)} terms)\n"
        )

        f.write("Interactions = [\n")
        for i, j in nn:
            f.write(f"  ['{j1_name}', 'SdotS', {i}, {j}],\n")
        for i, j in nnn:
            f.write(f"  ['{j2_name}', 'SdotS', {i}, {j}],\n")
        for cpl, op, i, j, k in ssc:
            f.write(f"  ['{cpl}', '{op}', {i}, {j}, {k}],\n")
        f.write("]\n\n")




        f.write("# Translation by a1 (== b1)\n")
        f.write(f"Translation_a1 = {perm_ta1}\n\n")
        f.write("# Translation by 2*a2 (== b2)\n")
        f.write(f"Translation_2a2 = {perm_t2a2}\n\n")

        f.write(f"# Full translation group of superlattice ({len(symmetries)} elements)\n")
        f.write("Symmetries = [\n")
        for p in symmetries:
            f.write(f"  {p},\n")
        f.write("]\n\n")

        f.write("# Irreducible representations\n")
        for sec in sections:
            f.write(f"\n[{sec['name']}]\n")
            f.write("characters = [\n")
            for chi in sec["characters"]:
                f.write(f"  [{chi.real:.16f}, {chi.imag:.16f}],\n")
            f.write("]\n")
            kx, ky = sec["momentum"]
            f.write(f"momentum = [{kx:.16f}, {ky:.16f}]\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("a", nargs="?", type=int, default=3)
    parser.add_argument("b", nargs="?", type=int, default=1)
    parser.add_argument("--toml", metavar="FILE", default=None)
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--nn-coupling-name", default="J1")
    parser.add_argument("--nnn-coupling-name", default="J2")
    parser.add_argument("--ssc-coupling-name", default="Jchi")
    parser.add_argument(
        "--ssc-orientation",
        default="up",
        help="Default orientation for all triangles: up/down/cw/ccw (default: up)"
    )
    args = parser.parse_args()

    cells, sites, T, TinvN, ncell, nsite = build_torus(args.a, args.b)

    perm_ta1 = compute_translation_perm(sites, TinvN, ncell, (1, 0))
    perm_t2a2 = compute_translation_perm(sites, TinvN, ncell, (0, 1))  # cell-step along b2 = 2*a2
    symmetries, displacements = build_symmetries(sites, cells, TinvN, ncell)
    sections = compute_irrep_sections(args.a, args.b, ncell, displacements)

    print(f"# Ncell={ncell}, Nsite={nsite} (always even)")
    print(f"# |Symmetries|={len(symmetries)}, |irreps|={len(sections)}")

    if args.verify:
        verify_perm(perm_ta1, "Translation_a1")
        verify_perm(perm_t2a2, "Translation_2a2")
        for i, p in enumerate(symmetries):
            verify_perm(p, f"Symmetry {i}")
        verify_sections(symmetries, sections)
        nnn = compute_nnn_bonds_unique(sites, TinvN, ncell)
        if len(nnn) != len(set(nnn)):
            raise AssertionError("Duplicate NNN pair found")
        print("# Verification: OK")

    if args.toml:
        tris = triangles(sites, TinvN, ncell)
        chiral_orientations = [args.ssc_orientation] * len(tris)

        write_toml(
            args.toml, sites, T, TinvN, ncell, nsite, args.a, args.b,
            perm_ta1, perm_t2a2, symmetries, displacements,
            j1_name=args.nn_coupling_name,
            j2_name=args.nnn_coupling_name,
            jchi_name=args.ssc_coupling_name,
            chiral_orientations=chiral_orientations,
        )
        print(f"# Wrote {args.toml}")


if __name__ == "__main__":
    main()
