#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The xdiag Contributors
"""Plot real-space or momentum-space views for lattices generated by genlatC6.py."""

import argparse

import matplotlib.pyplot as plt
import numpy as np

from cantedAFM.Latscripts.genlatC6 import (
    _build_site_lookup,
    _frac_mod_cell,
    build_torus,
    compute_nn_bonds,
    compute_rotation_perm,
    enumerate_momenta,
    site_to_cart,
)


def _torus_vectors_cart(T):
    """Return the torus superlattice vectors in Cartesian coordinates."""
    a1 = np.array([1.0, 0.0])
    a2 = np.array([0.5, np.sqrt(3.0) / 2.0])
    t1 = float(T[0, 0]) * a1 + float(T[1, 0]) * a2
    t2 = float(T[0, 1]) * a1 + float(T[1, 1]) * a2
    return t1, t2


def _select_wigner_seitz_image(coord, t1, t2, search_radius=2, tol=1e-10):
    """Choose the periodic image closest to the origin (Wigner-Seitz representative)."""
    basis = np.column_stack((t1, t2))
    coeff = np.linalg.solve(basis, coord)
    center = np.rint(coeff).astype(int)

    candidates = []
    for dm in range(-search_radius, search_radius + 1):
        for dn in range(-search_radius, search_radius + 1):
            m = int(center[0] + dm)
            n = int(center[1] + dn)
            image = coord - m * t1 - n * t2
            norm2 = float(np.dot(image, image))
            candidates.append((norm2, float(image[0]), float(image[1]), m, n, image))

    best_norm2 = min(item[0] for item in candidates)
    finalists = [item for item in candidates if item[0] <= best_norm2 + tol]
    finalists.sort(key=lambda item: (round(item[1], 12), round(item[2], 12), item[3], item[4]))
    return finalists[0][5]


def _display_coords(coords, T, mode):
    """Return plotting coordinates for the requested display mode."""
    if mode == "canonical":
        return coords

    if mode != "wigner-seitz":
        raise ValueError(f"Unknown display coordinate mode: {mode}")

    t1, t2 = _torus_vectors_cart(T)
    disp = np.array([_select_wigner_seitz_image(coord, t1, t2) for coord in coords])
    return disp


def _classify_high_symmetry(fq1, fq2, ncell):
    if (fq1, fq2) == (0, 0):
        return "Gamma"

    if ncell % 3 == 0:
        if 3 * fq1 == 2 * ncell and 3 * fq2 == ncell:
            return "K"
        if 3 * fq1 == ncell and 3 * fq2 == 2 * ncell:
            return "Kp"

    if ncell % 2 == 0:
        h = ncell // 2
        if (fq1, fq2) in {(h, 0), (0, h), (h, h)}:
            return "M"

    return "generic"


def plot_real_space(
    a,
    b,
    show_indices=False,
    show_bonds=True,
    show_rotation_labels=False,
    display_coordinates="canonical",
):
    cells, sites, T, t_inv_n, ncell, nsite = build_torus(a, b)

    coords_canonical = np.array([site_to_cart(site) for site in sites])
    coords = _display_coords(coords_canonical, T, display_coordinates)
    fig, ax = plt.subplots(figsize=(7.5, 7.0))

    if show_bonds:
        bonds = compute_nn_bonds(sites, t_inv_n, ncell)
        for i, j in bonds:
            xi, yi = coords[i]
            xj, yj = coords[j]
            ax.plot([xi, xj], [yi, yj], color="0.75", linewidth=1.0, zorder=1)

    is_a = np.array([site[2] == 0 for site in sites])
    ax.scatter(coords[is_a, 0], coords[is_a, 1], s=45, c="#1f77b4", label="A", zorder=3)
    ax.scatter(coords[~is_a, 0], coords[~is_a, 1], s=45, c="#d62728", label="B", zorder=3)

    if show_indices:
        for idx, (x, y) in enumerate(coords):
            ax.annotate(str(idx), (x, y), textcoords="offset points", xytext=(4, 4), fontsize=8)

    if show_rotation_labels:
        lookup = _build_site_lookup(sites, t_inv_n, ncell)
        perm_rot = compute_rotation_perm(sites, t_inv_n, ncell)

        _arrow_kw = dict(
            arrowstyle="-|>",
            color="#ff7f0e",
            lw=1.2,
            mutation_scale=10,
        )

        for idx, (n1, n2, sub) in enumerate(sites):
            x, y = coords[idx]
            key = (_frac_mod_cell((n1, n2), t_inv_n, ncell), sub)
            lookup_idx = lookup[key]
            rot_idx = perm_rot[idx]

            # Label for this site (blue, upper-left)
            ax.annotate(
                str(lookup_idx),
                (x, y),
                textcoords="offset points",
                xytext=(-12, 6),
                fontsize=8,
                color="#1f77b4",
                fontweight="bold",
            )
            # Label of the rotation target (orange, lower-right)
            ax.annotate(
                str(rot_idx),
                (x, y),
                textcoords="offset points",
                xytext=(8, -10),
                fontsize=8,
                color="#ff7f0e",
                fontweight="bold",
            )

            # Arrow from this site to its image under R6
            x_rot, y_rot = coords[rot_idx]
            # Shorten arrow slightly so it doesn't overlap site markers
            shrink = 0.08
            dx, dy = x_rot - x, y_rot - y
            length = np.hypot(dx, dy)
            if length > 1e-6:
                ux, uy = dx / length, dy / length
                x_start = x + ux * shrink
                y_start = y + uy * shrink
                x_end = x_rot - ux * shrink
                y_end = y_rot - uy * shrink
                ax.annotate(
                    "",
                    xy=(x_end, y_end),
                    xytext=(x_start, y_start),
                    arrowprops=_arrow_kw,
                    zorder=2,
                )

        # Legend entries for the two label layers
        ax.scatter([], [], c="#1f77b4", marker="$i$", label="Lookup index")
        ax.scatter([], [], c="#ff7f0e", marker="$R$", label="Rotated index → R6(i)")

    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_title(
        "Honeycomb real space "
        f"(a={a}, b={b}, Ncell={ncell}, Nsite={nsite}, display={display_coordinates})"
    )
    ax.legend(loc="best")
    ax.grid(alpha=0.2)

    return fig


def plot_momentum_space(a, b):
    _, _, _, _, ncell, _ = build_torus(a, b)
    momenta = enumerate_momenta(a, b, ncell)

    fig, ax = plt.subplots(figsize=(7.5, 7.0))

    groups = {"generic": [], "Gamma": [], "K": [], "Kp": [], "M": []}
    for fq1, fq2, _, _, kx, ky in momenta:
        cls = _classify_high_symmetry(fq1, fq2, ncell)
        groups[cls].append((fq1, fq2, kx, ky))

    if groups["generic"]:
        xy = np.array([(p[2], p[3]) for p in groups["generic"]])
        ax.scatter(xy[:, 0], xy[:, 1], s=28, c="0.6", label="Generic", zorder=2)

    styles = {
        "Gamma": ("#2ca02c", "o", 110),
        "K": ("#ff7f0e", "^", 100),
        "Kp": ("#9467bd", "v", 100),
        "M": ("#d62728", "s", 90),
    }

    for name in ("Gamma", "K", "Kp", "M"):
        pts = groups[name]
        if not pts:
            continue
        color, marker, size = styles[name]
        xy = np.array([(p[2], p[3]) for p in pts])
        ax.scatter(xy[:, 0], xy[:, 1], s=size, c=color, marker=marker, label=name, zorder=3)

        for idx, (_, _, kx, ky) in enumerate(pts):
            label = name if name != "M" else f"M{idx + 1}"
            ax.annotate(label, (kx, ky), textcoords="offset points", xytext=(5, 6), fontsize=9)

    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel(r"$k_x$")
    ax.set_ylabel(r"$k_y$")
    ax.set_title(f"Allowed momenta (a={a}, b={b}, Ncell={ncell})")
    ax.grid(alpha=0.25)
    ax.legend(loc="best")

    return fig


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("space", choices=["real", "momentum"],
                        help="Which space to plot: real or momentum")
    parser.add_argument("a", nargs="?", type=int, default=3,
                        help="Torus parameter a (default: 3)")
    parser.add_argument("b", nargs="?", type=int, default=0,
                        help="Torus parameter b (default: 0)")
    parser.add_argument("--show-indices", action="store_true",
                        help="Annotate site indices in real-space plot")
    parser.add_argument("--show-bonds", dest="show_bonds", action="store_true",
                        help="Display nearest-neighbor bonds in real-space plot (default)")
    parser.add_argument("--no-show-bonds", dest="show_bonds", action="store_false",
                        help="Hide nearest-neighbor bonds in real-space plot")
    parser.add_argument("--show-rotation-labels", action="store_true",
                        help="Overlay lookup and rotated site indices in different colors")
    parser.add_argument("--display-coordinates", choices=["canonical", "wigner-seitz"],
                        default="canonical",
                        help="Real-space coordinate representatives to plot (default: canonical)")
    parser.set_defaults(show_bonds=True)
    parser.add_argument("--save", metavar="FILE", default=None,
                        help="Save figure to FILE (png/pdf/...) instead of only showing it")
    parser.add_argument("--dpi", type=int, default=160,
                        help="DPI for saved figure (default: 160)")
    parser.add_argument("--no-show", action="store_true",
                        help="Do not open interactive window")
    args = parser.parse_args()

    if args.space == "real":
        fig = plot_real_space(
            args.a,
            args.b,
            show_indices=args.show_indices,
            show_bonds=args.show_bonds,
            show_rotation_labels=args.show_rotation_labels,
            display_coordinates=args.display_coordinates,
        )
    else:
        fig = plot_momentum_space(args.a, args.b)

    if args.save:
        fig.savefig(args.save, dpi=args.dpi, bbox_inches="tight")
        print(f"Saved {args.space} plot to {args.save}")

    if not args.no_show:
        plt.show()


if __name__ == "__main__":
    main()

